"""empty message

Revision ID: c7160087d840
Revises: 1a3a43067dbb
Create Date: 2024-01-15 17:02:12.258554

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'c7160087d840'
down_revision = '1a3a43067dbb'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('apps', schema=None) as batch_op:
        batch_op.add_column(sa.Column('link', sa.String(length=80), nullable=True))

    with op.batch_alter_table('users', schema=None) as batch_op:
        batch_op.add_column(sa.Column('app_id', sa.Integer(), nullable=True))
        batch_op.create_foreign_key(None, 'apps', ['app_id'], ['id'])

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('users', schema=None) as batch_op:
        batch_op.drop_constraint(None, type_='foreignkey')
        batch_op.drop_column('app_id')

    with op.batch_alter_table('apps', schema=None) as batch_op:
        batch_op.drop_column('link')

    # ### end Alembic commands ###
